# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./docker # ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        # image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - guacnetwork_compose
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './sys-data:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

    ### GUACAMOLE

    guacd:
        container_name: guacd_compose
        platform: linux/amd64
        image: guacamole/guacd
        networks:
            - guacnetwork_compose
        restart: unless-stopped
        # volumes:
        #    - ./drive:/drive:rw
        #    - ./record:/record:rw
    # postgres
    postgres:
        container_name: postgres_guacamole_compose
    #    platform: linux/amd64
        environment:
            PGDATA: /var/lib/postgresql/data/guacamole
            POSTGRES_DB: ${GUACAMOLE_DATABASE}
            POSTGRES_PASSWORD: ${GUACAMOLE_DATABASE_PASSWORD}
            POSTGRES_USER: ${GUACAMOLE_DATABASE_USER}
        image: postgres:13.4-buster
        networks:
            - guacnetwork_compose
        restart: unless-stopped
        ports:
            - 5432:5432
        volumes:
            - ./init:/docker-entrypoint-initdb.d
            - ./data:/var/lib/postgresql/data

    # guacamole
    guacamole:
        container_name: guacamole_compose
        platform: linux/amd64
        depends_on:
            - guacd
            - postgres
        environment:
            GUACD_HOSTNAME: guacd
            POSTGRES_DATABASE: ${GUACAMOLE_DATABASE}
            POSTGRES_HOSTNAME: postgres
            POSTGRES_PASSWORD: ${GUACAMOLE_DATABASE_PASSWORD}
            POSTGRES_USER: ${GUACAMOLE_DATABASE_USER}
        image: guacamole/guacamole
        links:
            - guacd
        networks:
            - guacnetwork_compose
        ports:
        ## enable next line if not using nginx
            - 8080:8080/tcp # Guacamole is on :8080/guacamole, not /.
        ## enable next line when using nginx
        ##    - 8080/tcp
        restart: unless-stopped

networks:
    sail:
        driver: bridge
    # guac network
    guacnetwork_compose:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
